### ISSUE TITLE
Source data in accessible data type 

### ISSUE THREAD

**Issue by fractastical** [svoitovych0218/multiversal-api#1]
Rather than a google doc maybe can have in a parsable .csv or some other data type that can easily be fed into a script?

**Comment by svoitovych0218** [comment]
Extended with API to receive inventory items collection as JSON
[Extend API](https://github.com/svoitovych0218/multiversal-api/commit/e3d7e1a0039d3fb548122c0f8903aa8e8e085f54)
[Adjust Readme](https://github.com/svoitovych0218/multiversal-api/commit/86f444ecba1400484dc68c30438d473dbdb7e8ee)
